-- ==========================================================
-- 1. BẢNG CHI NHÁNH
-- ==========================================================
CREATE TABLE BRANCHES (
    branch_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name        VARCHAR2(100) NOT NULL,
    address            VARCHAR2(255),
    city               VARCHAR2(100),
    country            VARCHAR2(100),
    phone_number       VARCHAR2(20)
);

-- ==========================================================
-- 2. BẢNG NHÂN VIÊN
-- ==========================================================
CREATE TABLE EMPLOYEES (
    employee_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR2(50) NOT NULL,
    last_name          VARCHAR2(50) NOT NULL,
    email              VARCHAR2(100) UNIQUE,
    phone_number       VARCHAR2(20),
    hire_date          DATE DEFAULT SYSDATE,
    salary             NUMBER(10,2),
    branch_id          NUMBER,

    CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 3. BẢNG KHÁCH HÀNG
-- ==========================================================
CREATE TABLE CUSTOMERS (
    customer_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name              VARCHAR2(100) NOT NULL,
    gender                     VARCHAR2(10),
    age                        NUMBER(3),
    country                    VARCHAR2(50),
    city                       VARCHAR2(50)
);

-- ==========================================================
-- 4. BẢNG SẢN PHẨM
-- ==========================================================
-- CREATE TABLE PRODUCTS (
--     product_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     product_name        VARCHAR2(200) NOT NULL,
--     category            VARCHAR2(100),
--     brand               VARCHAR2(100),
--     stock_quantity      NUMBER DEFAULT 0,
--     unit_price_usd      NUMBER(10,2),
--     branch_id           NUMBER,
--
--     CONSTRAINT fk_prod_branch
--         FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
-- );
--Phân mảnh dọc 1 (thông tin sp)
CREATE TABLE PRODUCTS_INFO (
product_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name        VARCHAR2(200) NOT NULL,
category            VARCHAR2(100),
brand               VARCHAR2(100)
);
--- Phân mảnh dọc 2 (kho sản phẩm)
CREATE TABLE PRODUCTS_STOCK (
    product_id          NUMBER,
    branch_id           NUMBER,
    stock_quantity      NUMBER DEFAULT 0,
    unit_price_usd      NUMBER(10,2),

    CONSTRAINT pk_products_stock
        PRIMARY KEY (product_id, branch_id),

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id),

    CONSTRAINT fk_stock_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);
-- ==========================================================
-- 5. BẢNG ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDERS (
    order_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_id         NUMBER,
    employee_id         NUMBER,
    branch_id           NUMBER,
    payment_method      VARCHAR2(50),
    tax_usd             NUMBER(10,2),
    total_price_usd     NUMBER(10,2),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),

    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id),

    CONSTRAINT fk_orders_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 6. BẢNG CHI TIẾT ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDER_ITEMS (
    order_id                NUMBER,
    product_id              NUMBER,
    quantity                NUMBER NOT NULL,
    discount_percent        NUMBER(5,2) DEFAULT 0,
    discount_amount_usd     NUMBER(10,2) DEFAULT 0,
    unit_price_usd          NUMBER(10,2),
    total_price_usd         NUMBER(10,2),

    CONSTRAINT pk_order_items
        PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),

    CONSTRAINT fk_items_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id)
);