-- ==========================================================
-- 1. BẢNG CHI NHÁNH
-- ==========================================================
CREATE TABLE BRANCHES (
    branch_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name        VARCHAR2(100) NOT NULL,
    address            VARCHAR2(255),
    city               VARCHAR2(100),
    country            VARCHAR2(100),
    phone_number       VARCHAR2(20)
);

-- ==========================================================
-- 2. BẢNG NHÂN VIÊN
-- ==========================================================
CREATE TABLE EMPLOYEES (
    employee_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR2(50) NOT NULL,
    last_name          VARCHAR2(50) NOT NULL,
    email              VARCHAR2(100) UNIQUE,
    phone_number       VARCHAR2(20),
    hire_date          DATE DEFAULT SYSDATE,
    salary             NUMBER(10,2),
    branch_id          NUMBER,

    CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 3. BẢNG KHÁCH HÀNG
-- ==========================================================
CREATE TABLE CUSTOMERS (
    customer_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name              VARCHAR2(100) NOT NULL,
    gender                     VARCHAR2(10),
    age                        NUMBER(3),
    country                    VARCHAR2(50),
    city                       VARCHAR2(50)
);

-- ==========================================================
-- 4. BẢNG SẢN PHẨM
-- ==========================================================
-- CREATE TABLE PRODUCTS (
--     product_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     product_name        VARCHAR2(200) NOT NULL,
--     category            VARCHAR2(100),
--     brand               VARCHAR2(100),
--     stock_quantity      NUMBER DEFAULT 0,
--     unit_price_usd      NUMBER(10,2),
--     branch_id           NUMBER,
--
--     CONSTRAINT fk_prod_branch
--         FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
-- );
--Phân mảnh dọc 1 (thông tin sp)
CREATE TABLE PRODUCTS_INFO (
product_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
product_name        VARCHAR2(200) NOT NULL,
category            VARCHAR2(100),
brand               VARCHAR2(100)
);
--- Phân mảnh dọc 2 (kho sản phẩm)
CREATE TABLE PRODUCTS_STOCK (
    product_id          NUMBER,
    branch_id           NUMBER,
    stock_quantity      NUMBER DEFAULT 0,
    unit_price_usd      NUMBER(10,2),

    CONSTRAINT pk_products_stock
        PRIMARY KEY (product_id, branch_id),

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id),

    CONSTRAINT fk_stock_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);
-- ==========================================================
-- 5. BẢNG ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDERS (
    order_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_id         NUMBER,
    employee_id         NUMBER,
    branch_id           NUMBER,
    payment_method      VARCHAR2(50),
    tax_usd             NUMBER(10,2),
    total_price_usd     NUMBER(10,2),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),

    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id),

    CONSTRAINT fk_orders_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 6. BẢNG CHI TIẾT ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDER_ITEMS (
    order_id                NUMBER,
    product_id              NUMBER,
    quantity                NUMBER NOT NULL,
    discount_percent        NUMBER(5,2) DEFAULT 0,
    discount_amount_usd     NUMBER(10,2) DEFAULT 0,
    unit_price_usd          NUMBER(10,2),
    total_price_usd         NUMBER(10,2),

    CONSTRAINT pk_order_items
        PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),

    CONSTRAINT fk_items_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id)
);

/
---thêm branch trước khi chạy file python fill data
---Them du lieu chi nhanh
INSERT ALL
    INTO BRANCHES (BRANCH_ID, BRANCH_NAME, ADDRESS, CITY, COUNTRY, PHONE_NUMBER)
    VALUES (1, 'Branch1', '633 West 5th Street, Suite 2600', 'Los Angeles', 'United States', '0854621598')

    INTO BRANCHES (BRANCH_ID, BRANCH_NAME, ADDRESS, CITY, COUNTRY, PHONE_NUMBER)
    VALUES (2, 'Branch2', '1 Park Row', 'Leeds', 'United Kingdom', '0254568547')

    INTO BRANCHES (BRANCH_ID, BRANCH_NAME, ADDRESS, CITY, COUNTRY, PHONE_NUMBER)
    VALUES (3, 'Branch3', '115 Grenfell Street', 'Adelaide', 'Australia', '0584621856')

SELECT * FROM dual;
commit;

---them du lieu product de du 1000 dong sau khi chạy python fill data
ALTER TABLE PRODUCTS_INFO
MODIFY product_id GENERATED BY DEFAULT AS IDENTITY RESTART START WITH 961;

INSERT INTO PRODUCTS_INFO (PRODUCT_NAME, CATEGORY, BRAND)
SELECT 'Wireless Noise Cancelling Headphones', 'Electronics', 'Sony' FROM DUAL UNION ALL
SELECT 'Cotton T-Shirt Basic', 'Clothing', 'Uniqlo' FROM DUAL UNION ALL
SELECT 'Smart LED Bulb WiFi', 'Home', 'Philips' FROM DUAL UNION ALL
SELECT 'Electric Toothbrush Rechargeable', 'Health', 'Oral-B' FROM DUAL UNION ALL
SELECT 'Moisturizing Skin Cream', 'Beauty', 'Loreal' FROM DUAL UNION ALL
SELECT 'Mechanical Pencil 0.5mm', 'Stationery', 'Pentel' FROM DUAL UNION ALL
SELECT 'Non-Stick Frying Pan', 'Kitchen', 'Tefal' FROM DUAL UNION ALL
SELECT 'Hiking Backpack 40L', 'Sports', 'North Face' FROM DUAL UNION ALL
SELECT 'Yoga Mat Eco-Friendly', 'Sports', 'Nike' FROM DUAL UNION ALL
SELECT 'Espresso Coffee Machine', 'Kitchen', 'DeLonghi' FROM DUAL UNION ALL
SELECT 'Bluetooth Speaker Waterproof', 'Electronics', 'JBL' FROM DUAL UNION ALL
SELECT 'Running Shorts Lightweight', 'Clothing', 'Adidas' FROM DUAL UNION ALL
SELECT 'Multivitamin Tablets', 'Health', 'Nature Made' FROM DUAL UNION ALL
SELECT 'Face Sunscreen SPF 50', 'Beauty', 'Anessa' FROM DUAL UNION ALL
SELECT 'Gel Ink Pens Black 10pk', 'Stationery', 'Pilot' FROM DUAL UNION ALL
SELECT 'Stainless Steel Water Bottle', 'Home', 'Hydro Flask' FROM DUAL UNION ALL
SELECT 'Adjustable Dumbbells Set', 'Sports', 'Bowflex' FROM DUAL UNION ALL
SELECT 'Wireless Gaming Mouse', 'Electronics', 'Logitech' FROM DUAL UNION ALL
SELECT 'Silk Necktie Striped', 'Clothing', 'Gucci' FROM DUAL UNION ALL
SELECT 'Air Purifier HEPA Filter', 'Home', 'Xiaomi' FROM DUAL UNION ALL
SELECT 'Organic Green Tea Bag', 'Food', 'Dilmah' FROM DUAL UNION ALL
SELECT 'Gaming Headset Surround Sound', 'Electronics', 'Razer' FROM DUAL UNION ALL
SELECT 'Leather Wallet Slim', 'Accessories', 'Montblanc' FROM DUAL UNION ALL
SELECT 'Automatic Umbrella Windproof', 'Accessories', 'Xiaomi' FROM DUAL UNION ALL
SELECT 'Laptop Stand Aluminum', 'Electronics', 'Baseus' FROM DUAL UNION ALL
SELECT 'Protein Bar Chocolate 12pk', 'Health', 'MyProtein' FROM DUAL UNION ALL
SELECT 'Scented Candle Lavender', 'Home', 'Yankee' FROM DUAL UNION ALL
SELECT 'Electric Kettle 1.7L', 'Kitchen', 'Philips' FROM DUAL UNION ALL
SELECT 'Polarized Sunglasses', 'Accessories', 'Ray-Ban' FROM DUAL UNION ALL
SELECT 'Basketball Size 7', 'Sports', 'Spalding' FROM DUAL UNION ALL
SELECT 'Dry Shampoo Spray', 'Beauty', 'Batiste' FROM DUAL UNION ALL
SELECT 'External Hard Drive 2TB', 'Electronics', 'Seagate' FROM DUAL UNION ALL
SELECT 'Ceramic Coffee Mug', 'Kitchen', 'Starbucks' FROM DUAL UNION ALL
SELECT 'Jump Rope Digital Counter', 'Sports', 'Nike' FROM DUAL UNION ALL
SELECT 'Hoodie Oversized', 'Clothing', 'H&M' FROM DUAL UNION ALL
SELECT 'Smart Door Lock Fingerprint', 'Home', 'Samsung' FROM DUAL UNION ALL
SELECT 'Foam Roller Muscle Recovery', 'Health', 'TriggerPoint' FROM DUAL UNION ALL
SELECT 'Wall Clock Minimalist', 'Home', 'Casio' FROM DUAL UNION ALL
SELECT 'Webcam 1080p Auto-focus', 'Electronics', 'Logitech' FROM DUAL UNION ALL
SELECT 'Duffel Bag Small', 'Sports', 'Puma' FROM DUAL;

COMMIT;

INSERT INTO PRODUCTS_STOCK (
    product_id,
    branch_id,
    stock_quantity,
    unit_price_usd
)
SELECT 961, 1, 120, 249.99 FROM DUAL UNION ALL
SELECT 962, 1, 300, 14.99 FROM DUAL UNION ALL
SELECT 963, 1, 180, 19.99 FROM DUAL UNION ALL
SELECT 964, 1, 90, 59.99 FROM DUAL UNION ALL
SELECT 965, 1, 150, 24.99 FROM DUAL UNION ALL
SELECT 966, 1, 220, 3.99 FROM DUAL UNION ALL
SELECT 967, 1, 80, 39.99 FROM DUAL UNION ALL
SELECT 968, 1, 65, 79.99 FROM DUAL UNION ALL
SELECT 969, 1, 110, 29.99 FROM DUAL UNION ALL
SELECT 970, 1, 45, 499.99 FROM DUAL UNION ALL
SELECT 971, 1, 130, 89.99 FROM DUAL UNION ALL
SELECT 972, 1, 200, 24.99 FROM DUAL UNION ALL
SELECT 973, 1, 160, 12.99 FROM DUAL UNION ALL
SELECT 974, 1, 140, 18.99 FROM DUAL UNION ALL
SELECT 975, 1, 260, 9.99 FROM DUAL UNION ALL
SELECT 976, 1, 170, 34.99 FROM DUAL UNION ALL
SELECT 977, 1, 50, 399.99 FROM DUAL UNION ALL
SELECT 978, 1, 75, 49.99 FROM DUAL UNION ALL
SELECT 979, 1, 40, 149.99 FROM DUAL UNION ALL
SELECT 980, 1, 95, 179.99 FROM DUAL UNION ALL
SELECT 981, 1, 350, 7.99 FROM DUAL UNION ALL
SELECT 982, 1, 85, 99.99 FROM DUAL UNION ALL
SELECT 983, 1, 100, 199.99 FROM DUAL UNION ALL
SELECT 984, 1, 120, 22.99 FROM DUAL UNION ALL
SELECT 985, 1, 160, 35.99 FROM DUAL UNION ALL
SELECT 986, 1, 280, 16.99 FROM DUAL UNION ALL
SELECT 987, 1, 90, 27.99 FROM DUAL UNION ALL
SELECT 988, 1, 70, 44.99 FROM DUAL UNION ALL
SELECT 989, 1, 115, 129.99 FROM DUAL UNION ALL
SELECT 990, 1, 100, 29.99 FROM DUAL UNION ALL
SELECT 991, 1, 150, 8.99 FROM DUAL UNION ALL
SELECT 992, 1, 60, 84.99 FROM DUAL UNION ALL
SELECT 993, 1, 190, 15.99 FROM DUAL UNION ALL
SELECT 994, 1, 140, 17.99 FROM DUAL UNION ALL
SELECT 995, 1, 105, 39.99 FROM DUAL UNION ALL
SELECT 996, 1, 80, 249.99 FROM DUAL UNION ALL
SELECT 997, 1, 130, 21.99 FROM DUAL UNION ALL
SELECT 998, 1, 170, 14.99 FROM DUAL UNION ALL
SELECT 999, 1, 95, 39.99 FROM DUAL UNION ALL
SELECT 1000, 1, 125, 34.99 FROM DUAL;

COMMIT;
