create database branch1tamp;
-- ==========================================================
-- 1. BẢNG CHI NHÁNH
-- ==========================================================
CREATE TABLE BRANCHES (
    branch_id          INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name        VARCHAR(100) NOT NULL,
    address            VARCHAR(255),
    city               VARCHAR(100),
    country            VARCHAR(100),
    phone_number       VARCHAR(20)
);

-- ==========================================================
-- 2. BẢNG NHÂN VIÊN
-- ==========================================================
CREATE TABLE EMPLOYEES (
    employee_id        INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR(50) NOT NULL,
    last_name          VARCHAR(50) NOT NULL,
    email              VARCHAR(100) UNIQUE,
    phone_number       VARCHAR(20),
    hire_date          DATE DEFAULT CURRENT_DATE,
    salary             NUMERIC(10,2),
    branch_id          INT8,

    CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 3. BẢNG KHÁCH HÀNG
-- ==========================================================
CREATE TABLE CUSTOMERS (
    customer_id                INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name              VARCHAR(100) NOT NULL,
    gender                     VARCHAR(10),
    age                        INT2,
    country                    VARCHAR(50),
    city                       VARCHAR(50)
);

-- ==========================================================
-- 4. BẢNG SẢN PHẨM (PHÂN MẢNH DỌC)
-- ==========================================================
--- Phân mảnh dọc 1 (thông tin sp)
CREATE TABLE PRODUCTS_INFO (
    product_id          INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name        VARCHAR(200) NOT NULL,
    category            VARCHAR(100),
    brand               VARCHAR(100)
);

--- Phân mảnh dọc 2 (kho sản phẩm)
CREATE TABLE PRODUCTS_STOCK (
    product_id          INT8,
    branch_id           INT8,
    stock_quantity      INT4 DEFAULT 0,
    unit_price_usd      NUMERIC(10,2),

    CONSTRAINT pk_products_stock
        PRIMARY KEY (product_id, branch_id),

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id),

    CONSTRAINT fk_stock_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 5. BẢNG ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDERS (
    order_id            INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    customer_id         INT8,
    employee_id         INT8,
    branch_id           INT8,
    payment_method      VARCHAR(50),
    tax_usd             NUMERIC(10,2),
    total_price_usd     NUMERIC(10,2),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),

    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id),

    CONSTRAINT fk_orders_branch
        FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id)
);

-- ==========================================================
-- 6. BẢNG CHI TIẾT ĐƠN HÀNG
-- ==========================================================
CREATE TABLE ORDER_ITEMS (
    order_id                INT8,
    product_id              INT8,
    quantity                INT4 NOT NULL,
    discount_percent        NUMERIC(5,2) DEFAULT 0,
    discount_amount_usd     NUMERIC(10,2) DEFAULT 0,
    unit_price_usd          NUMERIC(10,2),
    total_price_usd         NUMERIC(10,2),

    CONSTRAINT pk_order_items
        PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),

    CONSTRAINT fk_items_product
        FOREIGN KEY (product_id) REFERENCES PRODUCTS_INFO(product_id)
);
delete from ORDERS;


-- ==========================================================
-- 1. INSERT DATA MẪU CHO BẢNG BRANCHES (CHI NHÁNH)
-- ==========================================================
INSERT INTO BRANCHES (branch_name, address, city, country, phone_number) VALUES
('Chi nhánh Miền Nam', '123 Nguyễn Thị Minh Khai, Quận 1', 'Hồ Chí Minh', 'Việt Nam', '028-39300001'),
('Chi nhánh Miền Bắc', '456 Trần Hưng Đạo, Hoàn Kiếm', 'Hà Nội', 'Việt Nam', '024-39400002'),
('Chi nhánh Miền Trung', '789 Lê Duẩn, Hải Châu', 'Đà Nẵng', 'Việt Nam', '0236-3950003');

-- ==========================================================
-- 2. INSERT DATA MẪU CHO BẢNG EMPLOYEES (NHÂN VIÊN)
-- ==========================================================
-- Lưu ý: branch_id lấy từ các id 1, 2, 3 vừa sinh tự động ở bảng BRANCHES
INSERT INTO EMPLOYEES (first_name, last_name, email, phone_number, hire_date, salary, branch_id) VALUES
('Huy', 'Đinh Lâm Quốc', 'huy.dinh@company.com', '0901234567', '2025-01-15', 1500.00, 1),
('An', 'Nguyễn Hoài', 'an.nguyen@company.com', '0912345678', '2025-03-01', 1400.00, 1),
('Bình', 'Trần Văn', 'binh.tran@company.com', '0923456789', '2024-06-20', 1800.00, 2),
('Chi', 'Lê Thị', 'chi.le@company.com', '0934567890', '2025-02-10', 1350.00, 3);

-- ==========================================================
-- 3. INSERT DATA MẪU CHO BẢNG CUSTOMERS (KHÁCH HÀNG)
-- ==========================================================
INSERT INTO CUSTOMERS (customer_name, gender, age, country, city) VALUES
('Nguyễn Văn Trung', 'Nam', 28, 'Việt Nam', 'Hồ Chí Minh'),
('Phạm Minh Thư', 'Nữ', 22, 'Việt Nam', 'Hà Nội'),
('Hoàng Đức Anh', 'Nam', 35, 'Việt Nam', 'Đà Nẵng'),
('John Doe', 'Nam', 40, 'USA', 'New York');

-- ==========================================================
-- 4. INSERT DATA MẪU CHO BẢNG SẢN PHẨM (PHÂN MẢNH DỌC)
-- ==========================================================
--- Chèn vào mảnh 1: PRODUCTS_INFO (Thông tin cơ bản)
INSERT INTO PRODUCTS_INFO (product_name, category, brand) VALUES
('iPhone 15 Pro Max 256GB', 'Điện thoại', 'Apple'),
('Samsung Galaxy S24 Ultra', 'Điện thoại', 'Samsung'),
('MacBook Pro M3 14 inch', 'Laptop', 'Apple'),
('Sony WH-1000XM5', 'Phụ kiện', 'Sony');

--- Chèn vào mảnh 2: PRODUCTS_STOCK (Số lượng và giá ở từng chi nhánh)
-- Giả sử phân phối sản phẩm về các chi nhánh khác nhau
INSERT INTO PRODUCTS_STOCK (product_id, branch_id, stock_quantity, unit_price_usd) VALUES
(1, 1, 50, 1199.00), -- iPhone 15 ở Chi nhánh 1
(1, 2, 30, 1199.00), -- iPhone 15 ở Chi nhánh 2
(2, 1, 40, 1299.00), -- Samsung S24 ở Chi nhánh 1
(3, 2, 15, 1999.00), -- MacBook ở Chi nhánh 2
(4, 3, 25, 399.00);  -- Tai nghe Sony ở Chi nhánh 3

-- ==========================================================
-- 5. INSERT DATA MẪU CHO BẢNG ORDERS (ĐƠN HÀNG)
-- ==========================================================
INSERT INTO ORDERS (customer_id, employee_id, branch_id, payment_method, tax_usd, total_price_usd) VALUES
(1, 1, 1, 'Thẻ tín dụng', 119.90, 1318.90), -- Khách 1 mua ở Chi nhánh 1, nhân viên 1 bán
(2, 3, 2, 'Tiền mặt', 319.80, 3517.80),    -- Khách 2 mua ở Chi nhánh 2, nhân viên 3 bán
(3, 4, 3, 'Chuyển khoản', 39.90, 438.90);   -- Khách 3 mua ở Chi nhánh 3, nhân viên 4 bán


-- ==========================================================
-- 6. INSERT DATA MẪU CHO BẢNG ORDER_ITEMS (CHI TIẾT ĐƠN HÀNG)
-- ==========================================================
INSERT INTO ORDER_ITEMS (order_id, product_id, quantity, discount_percent, discount_amount_usd, unit_price_usd, total_price_usd) VALUES
(1, 1, 1, 0.00, 0.00, 1199.00, 1199.00),         -- Đơn 1 mua 1 chiếc iPhone 15
(2, 1, 1, 5.00, 59.95, 1199.00, 1139.05),         -- Đơn 2 mua 1 chiếc iPhone 15 (giảm giá 5%)
(2, 3, 1, 0.00, 0.00, 1999.00, 1999.00),         -- Đơn 2 mua thêm 1 chiếc MacBook
(3, 4, 1, 10.00, 39.90, 399.00, 359.10);         -- Đơn 3 mua 1 chiếc tai nghe Sony (giảm 10%)

